const posiciones = [
  {
    open_position: {
      candidate_id: 22,
      id: 1,
      is_open: false,
      position_name: "Desarrollador Frontend",
      project_id: 1,
    },
    project: {
      customer_id: 13,
      description: "Descripción Proyecto prueba",
      id: 1,
      is_team_complete: true,
      name: "Proyecto prueba",
    },
    soft_skill_ids: [1, 2],
    technology_ids: [1, 1],
  },
  {
    open_position: {
      candidate_id: 51,
      id: 2,
      is_open: false,
      position_name: "Desarrollador Backend",
      project_id: 1,
    },
    project: {
      customer_id: 13,
      description: "Descripción Proyecto prueba",
      id: 1,
      is_team_complete: true,
      name: "Proyecto prueba",
    },
    soft_skill_ids: [4, 4],
    technology_ids: [2, 6],
  },
  {
    open_position: {
      candidate_id: null,
      id: 3,
      is_open: true,
      position_name: "Desarrollador Frontend",
      project_id: 2,
    },
    project: {
      customer_id: 59,
      description: "Descripción Proyecto prueba",
      id: 2,
      is_team_complete: false,
      name: "Proyecto prueba",
    },
    soft_skill_ids: [1, 2],
    technology_ids: [1, 1],
  },
  {
    open_position: {
      candidate_id: null,
      id: 4,
      is_open: true,
      position_name: "Desarrollador Backend",
      project_id: 2,
    },
    project: {
      customer_id: 59,
      description: "Descripción Proyecto prueba",
      id: 2,
      is_team_complete: false,
      name: "Proyecto prueba",
    },
    soft_skill_ids: [4, 4],
    technology_ids: [2, 6],
  },
  {
    open_position: {
      candidate_id: null,
      id: 5,
      is_open: true,
      position_name: "FrontEnd Engineer",
      project_id: 3,
    },
    project: {
      customer_id: 13,
      description:
        "Este es un pequeño proyecto que busca cambiar la vida de todos.",
      id: 3,
      is_team_complete: false,
      name: "My little first Proyect",
    },
    soft_skill_ids: [6, 6, 6, 4, 4, 4, 7, 7, 7],
    technology_ids: [3, 5, 23, 3, 5, 23, 3, 5, 23],
  },
  {
    open_position: {
      candidate_id: null,
      id: 6,
      is_open: true,
      position_name: "Desarrollador Frontend",
      project_id: 11,
    },
    project: {
      customer_id: 13,
      description: "Descripción proyecto pruebax",
      id: 11,
      is_team_complete: false,
      name: "Mi proyectoy",
    },
    soft_skill_ids: [1, 2],
    technology_ids: [1, 1],
  },
  {
    open_position: {
      candidate_id: null,
      id: 7,
      is_open: true,
      position_name: "Desarrollador Backend",
      project_id: 11,
    },
    project: {
      customer_id: 13,
      description: "Descripción proyecto pruebax",
      id: 11,
      is_team_complete: false,
      name: "Mi proyectoy",
    },
    soft_skill_ids: [4, 4],
    technology_ids: [2, 6],
  },
  {
    open_position: {
      candidate_id: null,
      id: 8,
      is_open: true,
      position_name: "DevOps",
      project_id: 12,
    },
    project: {
      customer_id: 13,
      description: "ÚLTIMO PROYECTO",
      id: 12,
      is_team_complete: false,
      name: "Proyecto Final II",
    },
    soft_skill_ids: [4, 1],
    technology_ids: [11, 11],
  },
];
