export const a = [
  {
    open_position: {
      candidate_id: 51,
      id: 3,
      is_open: false,
      position_name: "Desarrollador Frontend",
      project_id: 2,
    },
    project: {
      customer_id: 59,
      description: "Descripción Proyecto prueba",
      id: 2,
      is_team_complete: false,
      name: "Proyecto prueba",
    },
    soft_skill_ids: [1, 2],
    technology_ids: [1, 1],
  },
  {
    open_position: {
      candidate_id: null,
      id: 4,
      is_open: true,
      position_name: "Desarrollador Backend",
      project_id: 2,
    },
    project: {
      customer_id: 59,
      description: "Descripción Proyecto prueba",
      id: 2,
      is_team_complete: false,
      name: "Proyecto prueba",
    },
    soft_skill_ids: [4, 4],
    technology_ids: [2, 6],
  },
  {
    open_position: {
      candidate_id: null,
      id: 9,
      is_open: true,
      position_name: "Backend Engineer",
      project_id: 14,
    },
    project: {
      customer_id: 59,
      description: "Este es un proyecto de prueba para probar la funcionalidad",
      id: 14,
      is_team_complete: false,
      name: "Camilo Project",
    },
    soft_skill_ids: [4, 4, 1, 1],
    technology_ids: [2, 7, 2, 7],
  },
  {
    open_position: {
      candidate_id: null,
      id: 10,
      is_open: true,
      position_name: "Backend Engineer",
      project_id: 14,
    },
    project: {
      customer_id: 59,
      description: "Este es un proyecto de prueba para probar la funcionalidad",
      id: 14,
      is_team_complete: false,
      name: "Camilo Project",
    },
    soft_skill_ids: [4, 4, 1, 1],
    technology_ids: [2, 7, 2, 7],
  },
  {
    open_position: {
      candidate_id: 20,
      id: 16,
      is_open: true,
      position_name: "Data scientist",
      project_id: 16,
    },
    project: {
      customer_id: 59,
      description: "Test project",
      id: 16,
      is_team_complete: false,
      name: "Test Project 5N",
    },
    soft_skill_ids: [7, 4],
    technology_ids: [18, 18],
  },
][
  ({
    open_position: {
      candidate_id: 51,
      id: 3,
      is_open: false,
      position_name: "Desarrollador Frontend",
      project_id: 2,
    },
    project: {
      customer_id: 59,
      description: "Descripción Proyecto prueba",
      id: 2,
      is_team_complete: false,
      name: "Proyecto prueba",
    },
    soft_skill_ids: [1, 2],
    technology_ids: [1, 1],
  },
  {
    open_position: {
      candidate_id: null,
      id: 4,
      is_open: true,
      position_name: "Desarrollador Backend",
      project_id: 2,
    },
    project: {
      customer_id: 59,
      description: "Descripción Proyecto prueba",
      id: 2,
      is_team_complete: false,
      name: "Proyecto prueba",
    },
    soft_skill_ids: [4, 4],
    technology_ids: [2, 6],
  },
  {
    open_position: {
      candidate_id: null,
      id: 9,
      is_open: true,
      position_name: "Backend Engineer",
      project_id: 14,
    },
    project: {
      customer_id: 59,
      description: "Este es un proyecto de prueba para probar la funcionalidad",
      id: 14,
      is_team_complete: false,
      name: "Camilo Project",
    },
    soft_skill_ids: [4, 4, 1, 1],
    technology_ids: [2, 7, 2, 7],
  },
  {
    open_position: {
      candidate_id: null,
      id: 10,
      is_open: true,
      position_name: "Backend Engineer",
      project_id: 14,
    },
    project: {
      customer_id: 59,
      description: "Este es un proyecto de prueba para probar la funcionalidad",
      id: 14,
      is_team_complete: false,
      name: "Camilo Project",
    },
    soft_skill_ids: [4, 4, 1, 1],
    technology_ids: [2, 7, 2, 7],
  },
  {
    open_position: {
      candidate_id: 20,
      id: 16,
      is_open: true,
      position_name: "Data scientist",
      project_id: 16,
    },
    project: {
      customer_id: 59,
      description: "Test project",
      id: 16,
      is_team_complete: false,
      name: "Test Project 5N",
    },
    soft_skill_ids: [7, 4],
    technology_ids: [18, 18],
  })
];
